apiVersion: v1
kind: Namespace
metadata:
  name: conclient
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: privileged-sa-conclient
  namespace: conclient
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: privileged-sa-conclient
subjects:
  - kind: ServiceAccount
    name: privileged-sa-conclient
    namespace: conclient
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conclient
  namespace: conclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conclient
  template:
    metadata:
      labels:
        app: conclient
    spec:
      serviceAccountName: privileged-sa-conclient
      containers:
        - name: container
          image: 'quay.io/luisarizmendi/con-in:latest'
          ports:
            - name: tcp-2049
              containerPort: 2049
              protocol: TCP
          env:
            - name: OUT_HOST
              value: 83.52.26.206
            - name: OUT_PORT
              value: '8443'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
              privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


