FROM ubuntu:22.04
# https://github.com/teal33t/obfuscated-openssh-server/tree/master

RUN apt-get update && apt-get install -y software-properties-common && \
    apt-add-repository ppa:zinglau/obfuscated-openssh && \
    apt-get update && \
    apt-get install -y ssh sshpass nmap openssh-server passwd iproute2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV OUT_HOST=configure-your-server \
    OUT_USER=root \
    OUT_PASS=R3dh4t1!supersecure \
    OUT_PORT=8443 \
    OUT_PORT_LOOPBACK=9122 \
    OUT_SSH_OBF_KEY=123qwersuper \
    IN_PASS=R3dh4t1!

USER root

RUN cat > /usr/local/bin/con-in.sh <<'EOF'
#!/bin/bash
/usr/sbin/sshd -D &
while true; do
    echo $OUT_PASS | sshpass ssh -N -o ObfuscateKeyword=$OUT_SSH_OBF_KEY -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o StrictHostKeyChecking=no  -p $OUT_PORT -R $OUT_PORT_LOOPBACK:localhost:9222  $OUT_USER@$OUT_HOST > /dev/null 2>&1
    sleep 60
done
EOF

RUN mkdir -p /root/.ssh/ && \
    mkdir -p /etc/ssh/ && \
    mkdir -p /run/sshd  && \
    chmod +x /usr/local/bin/con-in.sh && \
    ssh-keygen -A  && \
    sed -i 's/#Port.*/Port 9222/' /etc/ssh/sshd_config && \
    sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/LogLevel .*/LogLevel DEBUG/' /etc/ssh/sshd_config && \
    ssh-keygen -A

RUN    echo "root:$IN_PASS" | chpasswd

EXPOSE 9222

CMD ["/bin/bash", "/usr/local/bin/con-in.sh"]
