FROM ubuntu:22.04

# https://github.com/teal33t/obfuscated-openssh-server/tree/master

RUN apt-get update && apt-get install -y software-properties-common && \
    apt-add-repository ppa:zinglau/obfuscated-openssh && \
    apt-get update && \
    apt-get install -y ssh iptables iproute2 sshpass && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV OUT_PASS=R3dh4t1!supersecure \
    OUT_PORT=8443 \
    OUT_SSH_OBF_KEY=123qwersuper \
    IN_PASS=R3dh4t1!


USER root


RUN cat > /usr/local/bin/con-out.sh <<'EOF'
#!/bin/bash
/usr/sbin/sshd -D &

while true; do
    echo "SSH tunneling..."
    echo $IN_PASS | sshpass  ssh -N -T -o ExitOnForwardFailure=yes -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -o StrictHostKeyChecking=no -p 9122 -D 0.0.0.0:8089 root@localhost

    echo "SSH tunnel disconnected. Reconnecting in 5 seconds..."
    sleep 5

done
EOF

RUN mkdir -p /root/.ssh/ && \
    mkdir -p /etc/ssh/ && \
    mkdir -p /run/sshd  && \
    ssh-keygen -A  && \
    chmod +x /usr/local/bin/con-out.sh && \
    echo "Port 2223" > /etc/ssh/sshd_config && \
    echo "ObfuscatedPort $OUT_PORT" >> /etc/ssh/sshd_config && \
    echo "ObfuscateKeyword $OUT_SSH_OBF_KEY" >> /etc/ssh/sshd_config && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    echo "Protocol 2" >> /etc/ssh/sshd_config && \
    echo "LogLevel INFO" >> /etc/ssh/sshd_config && \
    echo "LoginGraceTime 120" >> /etc/ssh/sshd_config && \
    echo "StrictModes yes" >> /etc/ssh/sshd_config && \
    echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "IgnoreRhosts yes" >> /etc/ssh/sshd_config && \
    echo "HostbasedAuthentication no" >> /etc/ssh/sshd_config && \
    echo "PermitEmptyPasswords no" >> /etc/ssh/sshd_config && \
    echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config && \
    echo "X11Forwarding yes" >> /etc/ssh/sshd_config && \
    echo "X11DisplayOffset 10" >> /etc/ssh/sshd_config && \
    echo "PrintMotd no" >> /etc/ssh/sshd_config && \
    echo "PrintLastLog yes" >> /etc/ssh/sshd_config && \
    echo "TCPKeepAlive yes" >> /etc/ssh/sshd_config && \
    echo "AcceptEnv LANG LC_*" >> /etc/ssh/sshd_config && \
    echo "Subsystem sftp /usr/lib/openssh/sftp-server" >> /etc/ssh/sshd_config && \
    echo "UsePAM yes" >> /etc/ssh/sshd_config && \
    echo "KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256" >> /etc/ssh/sshd_config && \
    echo "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr" >> /etc/ssh/sshd_config && \
    echo "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com" >> /etc/ssh/sshd_config

RUN    echo "root:$OUT_PASS" | chpasswd

EXPOSE 2223 8443 8089

CMD ["/bin/bash", "/usr/local/bin/con-out.sh"]
